# Generated by Django 3.0.4 on 2020-03-30 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, verbose_name='ニックネーム')),
                ('gender', models.CharField(choices=[('1', '男性'), ('2', '女性')], max_length=2, verbose_name='性別')),
                ('days', models.CharField(blank=True, max_length=100, null=True, verbose_name='定刻出勤')),
                ('days_late', models.CharField(blank=True, max_length=100, null=True, verbose_name='遅れ出勤')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
